//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ust
{
    using System;
    using System.Collections.Generic;
    
    public partial class guests
    {
        public int id { get; set; }
        public Nullable<int> guest_id { get; set; }
        public Nullable<int> room_id { get; set; }
        public Nullable<System.DateTime> checkln { get; set; }
        public Nullable<System.DateTime> checkOut { get; set; }
    }
}
