//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ust
{
    using System;
    using System.Collections.Generic;
    
    public partial class ro0ms
    {
        public int id { get; set; }
        public string category { get; set; }
        public string status { get; set; }
        public string floor { get; set; }
        public string number { get; set; }
    }
}
